version: "3.8"
services:

  # PHP service
  phpfpm:
    image: php:8-fpm
    container_name: phpfpm
    volumes:
      - ./html:/var/www/html/
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: MySQL
    ports:
      - "3306:3306"  # Mapeo del puerto correcto de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: Mangorfid
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql/init_rfid.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx
    container_name: Nginx
    working_dir: /etc/nginx
    ports:
      - 88:80
    volumes:
      - ./html:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/var/log/nginx/
    depends_on:
      - phpfpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
