version: '3.8'

services:
  # PHP service
  phpfpm:
    image: php:8-fpm
    container_name: phpfpm
    volumes:
      - ./html:/var/www/html/
    networks:
      - app-network
    restart: always

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "1234:3306"  # Exponer puerto 3306 para conexión con MySQL
    environment:
      MYSQL_ROOT_PASSWORD: Mangorfid
      MYSQL_DATABASE: rfid  # Crea la base de datos si no existe
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro  # Montar el archivo SQL para inicialización
      - db_data:/var/lib/mysql               # Persistencia de datos
    networks:
      - app-network
    restart: always

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Conexión al contenedor MySQL
      PMA_USER: root
      PMA_PASSWORD: Mangorfid
    ports:
      - 8080:80
    networks:
      - app-network
    restart: always

  # Nginx service
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 88:80
    volumes:
      - ./html:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/var/log/nginx/
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
